services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.4'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'