services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.4'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    command:
      - sh
      - -c
      - |
        bin/elasticsearch-plugin install analysis-nori &&
        bin/elasticsearch-plugin list &&
        exec docker-entrypoint.sh elasticsearch
    ports:
      - '9200:9200'